// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Opt_Func_FullMethodName = "/Opt/Func"
)

// OptClient is the client API for Opt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptClient interface {
	Func(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type optClient struct {
	cc grpc.ClientConnInterface
}

func NewOptClient(cc grpc.ClientConnInterface) OptClient {
	return &optClient{cc}
}

func (c *optClient) Func(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, Opt_Func_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptServer is the server API for Opt service.
// All implementations must embed UnimplementedOptServer
// for forward compatibility
type OptServer interface {
	Func(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedOptServer()
}

// UnimplementedOptServer must be embedded to have forward compatible implementations.
type UnimplementedOptServer struct {
}

func (UnimplementedOptServer) Func(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Func not implemented")
}
func (UnimplementedOptServer) mustEmbedUnimplementedOptServer() {}

// UnsafeOptServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptServer will
// result in compilation errors.
type UnsafeOptServer interface {
	mustEmbedUnimplementedOptServer()
}

func RegisterOptServer(s grpc.ServiceRegistrar, srv OptServer) {
	s.RegisterService(&Opt_ServiceDesc, srv)
}

func _Opt_Func_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptServer).Func(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Opt_Func_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptServer).Func(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Opt_ServiceDesc is the grpc.ServiceDesc for Opt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Opt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Opt",
	HandlerType: (*OptServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Func",
			Handler:    _Opt_Func_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
